name: Temp Versioning for Testing

on:
  # Allow running manually from Actions tab
  workflow_dispatch:

permissions: write-all

jobs:
  test_versioning:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    # Autoversioning and updating changelog:
    - name: Conventional Changelog Action
      id: changelog
      uses: TriPSs/conventional-changelog-action@v5.2.1
      with:
        github-token: ${{ secrets.REPO_TOKEN_SECRET }}

    - name: Create Release
      uses: actions/create-release@v1
      if: ${{ steps.changelog.outputs.skipped == 'false' }}
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN_SECRET }}
      with:
        tag_name: ${{ steps.changelog.outputs.tag }}
        release_name: ${{ steps.changelog.outputs.tag }}
        body: ${{ steps.changelog.outputs.clean_changelog }}
